# Generated by Django 3.1.1 on 2021-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('confirmation_number', models.CharField(max_length=100)),
                ('reset_code', models.CharField(max_length=100)),
                ('avatar', models.ImageField(null=True, upload_to='avatars/')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
