# Generated by Django 3.2.9 on 2021-12-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_code',
            field=models.IntegerField(null=True),
        ),
    ]
