# Generated by Django 3.2.9 on 2021-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
