# Generated by Django 3.2.9 on 2021-12-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0003_test_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
    ]
