# Generated by Django 3.2.9 on 2022-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0005_test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(default='Matematyka', max_length=100),
            preserve_default=False,
        ),
    ]
