# Generated by Django 3.2.9 on 2022-01-22 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials', '0007_solvedtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedtest',
            name='test',
            field=models.ManyToManyField(null=True, related_name='answers', to='trials.Test'),
        ),
        migrations.AlterField(
            model_name='solvedtest',
            name='user',
            field=models.ManyToManyField(null=True, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
